<?php ?>
    <li style="list-style: none;">
        <a class="share flex justify-around align-items-center pointer color-primary back-fff border-fff border-primary-hover color-fff-hover back-primary-hover plr-5 ptb-5 rounded-5" style="width:25px;height:auto;"><i class="fal fa-share-alt" data-link="https://<?php echo $_SERVER['HTTP_HOST'].'/'.pagename($mystring).'/?'.$shareTarget.'='.${$shareTarget};?>" data-title="<?php echo txtLang('Know more about '.getLangArray($pulledData[0][$pulledKeys[2]]).' on '.$_SERVER['HTTP_HOST'].'','تعرف المزيد على '.getLangArray($pulledData[0][$pulledKeys[2]]).' على موقع '.$_SERVER['HTTP_HOST'].'',$_SERVER['HTTP_HOST'].'’da ' . getLangArray($pulledData[0][$pulledKeys[2]]).' hakkinda artık bulun');?>"></i></a>
    </li>
    <li style="list-style: none;">
        <a class="facebook flex justify-around align-items-center color-primary back-fff border-fff border-primary-hover color-fff-hover back-primary-hover plr-5 ptb-5 rounded-5" style="width:25px;height:auto;" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode('https://'.$_SERVER['HTTP_HOST'].'/'.pagename($mystring).'/?'.$shareTarget.'='.${$shareTarget});?>&display=popup&ref=plugin&src=like"><i class="fab fa-facebook-f stroke"></i></a>
    </li>
    <li style="list-style: none;">
        <a class="twitter flex justify-around align-items-center color-primary color-fff-hover border-fff border-primary-hover back-fff back-primary-hover plr-5 ptb-5 rounded-5" style="width:25px;height:auto;" target="_blank" href="https://twitter.com/intent/tweet?<?php echo '&url='.urlencode('https://'.$_SERVER['HTTP_HOST'].'/'.pagename($mystring).'/?'.$shareTarget.'='.${$shareTarget}).'&text='.txtLang('Know more about '.getLangArray($pulledData[0][$pulledKeys[2]]).' on '.$_SERVER['HTTP_HOST'].'','تعرف المزيد على '.getLangArray($pulledData[0][$pulledKeys[2]]).' على موقع '.$_SERVER['HTTP_HOST'].'',$_SERVER['HTTP_HOST'].'’da ' . getLangArray($pulledData[0][$pulledKeys[2]]).' hakkinda artık bulun');?>&data-size=large"><i class="fab fa-twitter stroke"></i></a>
    </li>
    <li style="list-style: none;">
        <a class="whatsapp flex justify-around align-items-center color-primary color-fff-hover border-fff border-primary-hover back-fff back-primary-hover plr-5 ptb-5 rounded-5" style="width:25px;height:auto;" target="_blank" href="https://wa.me/?text=<?php echo urlencode('https://'.$_SERVER['HTTP_HOST'].'/'.pagename($mystring).'/?'.$shareTarget.'='.${$shareTarget}.'  '.txtLang('Know more about '.getLangArray($pulledData[0][$pulledKeys[2]]).' on '.$_SERVER['HTTP_HOST'].'','تعرف المزيد على '.getLangArray($pulledData[0][$pulledKeys[2]]).' على موقع '.$_SERVER['HTTP_HOST'].'',$_SERVER['HTTP_HOST'].'’da ' . getLangArray($pulledData[0][$pulledKeys[2]]).' hakkinda artık bulun'));?>"><i class="fab fa-whatsapp"></i></a>
    </li>
